// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp1_T1.Data;

#nullable disable

namespace WebApp1_T1.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20260923164824_MigrationInit")]
    partial class MigrationInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("WebApp1_T1.Data.Workshop", b =>
                {
                    b.Property<string>("workshop")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("equipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("workshop");

                    b.ToTable("Workshop");
                });
#pragma warning restore 612, 618
        }
    }
}
